name: .NET Framework Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build .NET Framework app on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: 'latest'

    - name: Restore NuGet packages
      run: nuget restore CyberSecChatBot.sln

    - name: Build Solution
      run: msbuild CyberSecChatBot.sln /p:Configuration=Release
